project/books/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, RadioField
from wtforms.validators import DataRequired


class AddBookForm(FlaskForm):
    isbn = StringField('ISBN', validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    year = StringField('Year', validators=[DataRequired()])

class BookSearchForm(FlaskForm):
    choices = [('ISBN', 'ISBN'),
               ('Title', 'Title'),
               ('Author', 'Author'),
               ('Year', 'Year')]
    select = SelectField('Search for', choices=choices)
    search = StringField('Value', validators=[DataRequired()])

class ReviewBookForm(FlaskForm):
    rating = RadioField('Rating', choices=[('1','1'),('2','2'),('3','3'),('4','4'),('5','5')])
    text = StringField('Text', render_kw={"placeholder": "Comments"})

project/books/views.py
# imports
from flask import render_template, Blueprint, request, redirect, url_for, flash, jsonify
from flask_login import login_required, current_user
from sqlalchemy import and_
from sqlalchemy.sql.expression import case
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import func
from datetime import datetime
import requests
import json

from project import db
from project.models import Book, Review, User
from .forms import AddBookForm, BookSearchForm, ReviewBookForm

# config
books_blueprint = Blueprint('books', __name__)

# helper functions
def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')

# routes
@books_blueprint.route('/')
def index():
    all_books = Book.query.all()
    return render_template('books.html', books=all_books)

@books_blueprint.route('/add', methods=['GET', 'POST'])
def add_book():
    form = AddBookForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_book = Book(form.isbn.data, form.title.data, form.author.data, form.year.data)
            db.session.add(new_book)
            db.session.commit()
            flash('New book, {}, added!'.format(new_book.title), 'success')
            return redirect(url_for('books.index'))
        else:
            flash_errors(form)
            flash('ERROR! Book was not added.', 'error')

    return render_template('add_book.html',form=form)

@books_blueprint.route('/search', methods=['GET', 'POST'])
@login_required
def search_book():
    search = BookSearchForm(request.form)
    if request.method == 'POST':
        return search_results(search)
    return render_template('search_book.html', form=search)

@books_blueprint.route('/results')
@login_required
def search_results(search):
    results = []
    search_string = search.data['search']

    if search_string:
        if search.data['select'] == 'ISBN':
            search_query = db.session.query(Book).filter(Book.isbn.contains(search_string))
        elif search.data['select'] == 'Title':
            search_query = db.session.query(Book).filter(Book.title.contains(search_string))
        elif search.data['select'] == 'Author':
            search_query = db.session.query(Book).filter(Book.author.contains(search_string))
        elif search.data['select'] == 'Year':
            search_query = db.session.query(Book).filter(Book.year == search_string)

    results = search_query.all()
    if not results:
        flash('No results found!', 'error')
        return redirect('/search')
    else:
        print(results)
        return render_template('books.html', books=results)

@books_blueprint.route('/book/<book_id>')
@login_required
def book_details(book_id):
    form = ReviewBookForm(request.form)
    book = db.session.query(Book)\
            .filter(Book.book_id == book_id)\
            .first()
    reviews = db.session.query(Review, User)\
            .outerjoin(User)\
            .filter(Review.book_id == book_id)\
            .filter(Review.user_id == User.user_id)\
            .all()

    goodreads = requests.get("https://www.goodreads.com/book/review_counts.json", params={'key': '53MbEMReRV6qWUw7IDg', "isbns": book.isbn}).json()

    if book is not None:
        return render_template('book_details.html', book=book, reviews=reviews, form=form, goodreads=goodreads)
    else:
        flash('Error! Book does not exist.', 'error')
    return redirect(url_for('books.index'))

@books_blueprint.route('/book/<book_id>', methods=['GET', 'POST'])
@login_required
def review_book(book_id):
    rating = request.form['rating']
    text = request.form['text']
    if request.method == 'POST':
        try:
            new_review = Review(current_user.user_id, book_id, rating, text, datetime.now())
            db.session.add(new_review)
            db.session.commit()
            flash('Review added!', 'success')
        except IntegrityError:
            flash('You already reviewed this book!', 'error')
        return redirect(url_for('books.book_details', book_id=book_id))

@books_blueprint.route("/api/<isbn>", methods=['GET'])
def book_api(isbn):
    if request.method == 'GET':
        book = db.session.query(Book).filter(Book.isbn == isbn).first()
        if book is None:
            return jsonify({"error": "Invalid isbn"}), 404

        reviews = db.session.query(func.count(Review.rating).label('count'), func.avg(Review.rating).label('average'))\
                .filter(Review.book_id == book.book_id)\
                .all()

        return jsonify({
                "title": book.title,
                "author": book.author,
                "year": book.year,
                "isbn": book.isbn,
                "review_count": reviews[0][0],
                "average_score": round(reviews[0][1], 1)
            })

project/users/views.py
# imports
from flask import render_template, Blueprint, request, redirect, url_for, flash, abort
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime

from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm
from project import db, mail, app
from project.models import User


# config
users_blueprint = Blueprint('users', __name__)


# helper functions
def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')

def send_async_email(msg):
    with app.app_context():
        mail.send(msg)

def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()

def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)

def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token = password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)

# routes
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data, datetime.now())
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)
                flash('Thanks for registering!  Please check your email to confirm your email address.', 'success')
                return redirect(url_for('books.index'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Username ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)

@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Thank you for confirming your email address!', 'success')

    return redirect(url_for('books.index'))

@users_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        flash('Email sent to confirm your email address. Please check your email!', 'success')
    except IntegrityError:
        flash('Error! Unable to send email to confirm your email address.', 'error')

    return redirect(url_for('users.user_profile'))

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('books.index'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('users.login'))

@users_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user.email)
            flash('Please check your email for a password reset link.', 'success')
        else:
            flash('Your email address must be confirmed before attempting a password reset.', 'error')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)

@users_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('The password reset link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)

@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    return render_template('user_profile.html')

@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.user_id).all()
        return render_template('admin_view_users.html', users=users)
    return redirect(url_for('stocks.watch_list'))

@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash('Email changed!  Please confirm your new email address (link sent to new email).', 'success')
                    return redirect(url_for('users.user_profile'))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form)


@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Password changed!', 'success')
            return redirect(url_for('users.user_profile'))

    return render_template('password_change.html', form=form)

project/templates/410.html
{% extends "layout.html" %}

{% block title %}
410
{% endblock %}

{% block content %}
 
  <h1>Gone</h1>
  <h4>The target resource is no longer available at the origin server and that this condition is likely to be permanent.</h4>
  <h4><a href="{{ url_for('books.index') }}">Book Reviews</a></h4>
 
{% endblock %}

project/templates/_form_macros.html
{% macro render_field(field) %}
 
 
<dt>{{ field.label }}:
 
<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
</dd>
 
 
{% endmacro %}

project/templates/add_book.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Add Book
{% endblock %}

{% block content %}
 
 
<div class="add-book">
 
<div class="page-header">
 
<h2>Add a New Book</h2>
 
  </div>
 
 
 
<form action="{{ url_for('books.add_book') }}" method="post">
    {{ form.csrf_token }}
 
<dl>
      {{ render_field(form.isbn, placeholder="Enter ISBN") }}
      {{ render_field(form.title, placeholder="Enter Title") }}
      {{ render_field(form.author, placeholder="Enter Author") }}
      {{ render_field(form.year, placeholder="Enter Year") }}
    </dl>
 
    <button class="btn btn-sm btn-success" type="submit">Add Book</button>
  </form>
 
</div>
 
 
{% endblock %}

project/templates/admin_view_users.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Admin View
{% endblock %}

{% block content %}
 
<div class="admin-view-users">
  <div class="page-header">
    <h2>Administrative Page: List of Users</h2>
  </div>
 
  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>Role</th>
          <th>Registration Date</th>
          <th>Email Confirmed?</th>
          <th>Email Confirmed On</th>
          <th>Last Login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.role }} </td>
            <td> {{ user.registered_on }} </td>
            <td> {{ user.email_confirmed }} </td>
            <td> {{ user.email_confirmed_on }} </td>
            <td> {{ user.last_logged_in }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
 
{% endblock %}

project/templates/book_details.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
{{ book.title }}
{% endblock %}

{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>{{ book.title }}</h2>
  </div>
 
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">Author</div>
      <div class="panel-body">{{ book.author}}</div>
    </div>
 
    <div class="panel panel-primary">
      <div class="panel-heading">Year</div>
      <div class="panel-body">{{ book.year }}</div>
    </div>
 
    <div class="panel panel-primary">
      <div class="panel-heading">ISBN</div>
      <div class="panel-body">{{ book.isbn }}</div>
    </div>

    {% if goodreads is not none %}
    <div class="panel panel-primary">
      <div class="panel-heading">Goodreads</div>
      <div class="panel-body">Average {{ goodreads['books'][0]['average_rating'] }} with {{ goodreads['books'][0]['ratings_count'] }} ratings</div>
    </div>
    {% endif %}
    
    {% if review is not none %}
    {% for review in reviews %}
    <div class="panel panel-primary">
      <div class="panel-heading">{{review.User.email}}: {{ review.Review.rating }}/5
        <span class="pull-right">{{ review.Review.date }}</span>
      </div>
      <div class="panel-body">{{ review.Review.text }}</div>
    </div>
    {% endfor %}
    {% endif %}
    
    <form action="{{ url_for('books.review_book', book_id = book.book_id) }}" method="post">
      {{ form.csrf_token }}
      <dl>
        <h4> Review: </h4>
        {% for button in form.rating %}
        <tr>
          <td>{{ button }}</td>
        </tr>
        <tr>
          <td>{{ button.label}}</td>
        </tr>
        {% endfor %}
        {{ form.text }}
      </dl>
      <button class="btn btn-sm btn-success" type="submit">Review Book</button>
    </form>
  </div>
</div>
 
{% endblock %}

project/templates/books.html
{% extends "layout.html" %}

{% block title %}
Books
{% endblock %}

{% block content %}
 
<div class="page-header">
  <h2>Books</h2>
</div>
<div class="row">
  <div class="col-md-4">
    <table class="table table-striped" id="owned_stock_table">
      <thead>
        <tr>
          <th>ISBN</th>
          <th>Title</th>
          <th>Author</th>
          <th>Year</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td>{{ book.isbn }}</td>
          <td><a href="{{ url_for('books.book_details', book_id=book.book_id) }}">{{ book.title }}</a></td>
          <td>{{ book.author }}</td>
          <td>{{ book.year }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
 
{% endblock %}

project/templates/email_confirmation.html
Your account on Book Reviews was successfully created.
Please click the link below to confirm your email address and
activate your account:
  
<a href="{{ confirm_url }}">{{ confirm_url }}</a>
 
--
Questions? Comments? Email wd50project1@gmail.com.

project/templates/email_password_reset.html
You requested that the password for your Book Reviews account be reset.
Please click the link below to reset your password:
 
<p>
<a href="{{ password_reset_url }}">{{ password_reset_url }}</a>
</p>
 
<p>
--<br>
Questions? Comments? Email wd50project1@gmail.com.
</p>

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="WD50-Project1-Books">
    <meta name="author" content="Vincent Leclair">
    <title>Book Reviews | {% block title %}{% endblock %}</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
 
  <body>
 
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
 
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#books-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('books.index') }}">Book Reviews</a>
        </div>
 
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="books-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('books.add_book') }}">Add Book</a></li>
              <li><a href="{{ url_for('books.search_book') }}">Search Book</a></li>
              <li><a href="{{ url_for('users.logout') }}">Log Out</a></li>
              {% if current_user.role == "admin" %}
              <li><a href="{{ url_for('users.admin_view_users') }}">View Users (Admin)</a></li>
              {% endif %}
            {% else %}
              <li><a href="{{ url_for('users.register') }}">Register</a></li>
              <li><a href="{{ url_for('users.login') }}">Log In</a></li>
            {% endif %}
          </ul> 
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('users.user_profile') }}">{{current_user.email}}</a></li>
            {% else %}
            <li><a href="#">Welcome!</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>
 
    <div class="container">
      <div class="content">
        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
        <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}
        
        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
        <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}
        
        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
        <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}
 
        <!-- child template -->
        {% block content %}
        {% endblock %}
 
      </div>
      <div class="footer">
        <hr>
        <p>Vincent Leclair - 2019</p>
      </div>
    </div><!-- /.container -->
 
    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

project/templates/login.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Login
{% endblock %}

{% block content %}
 
<div class="user-registration">
  <div class="page-header">
    <h2>Log In</h2>
  </div>
    <form action="{{ url_for('users.login') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email") }}
      {{ render_field(form.password, placeholder="Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Log In</button>
  </form>
  <p><em>Need an account? </em><a href="/register">Signup!</a></p>
  <p><em>Forgot your password? </em><a href="/reset">Reset!</a></p>
</div>
 
{% endblock %}

project/templates/password_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Change Password
{% endblock %}
{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>Password Change</h2>
  </div>
 
  <form action="{{ url_for('users.user_password_change') }} method="POST"">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Enter New Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>
 
{% endblock %}

project/templates/register.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Register
{% endblock %}

{% block content %}
<div class="user-registration">
  <div class="page-header">
    <h2>Register Your Account</h2>
  </div>
<form action="{{ url_for('users.register') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email") }}
      {{ render_field(form.password, placeholder="Password") }}
      {{ render_field(form.confirm, placeholder="Confirm password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Register</button>
  </form>
</div>
 
{% endblock %}

project/templates/reset_password_with_token.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Password Reset
{% endblock %}

{% block content %}
 
<div class="add-recipe">
  <div class="page-header">
    <h2>New Password:</h2>
  </div>
  <form action="{{ url_for('users.reset_with_token', token=token) }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Enter New Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>
 
{% endblock %}

project/templates/search_book.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
Search Book
{% endblock %}

{% block content %}

<div class="search-book">
  <div class="page-header">
    <h2>Search for a Book</h2>
  </div>
  <form action="{{ url_for('books.search_book') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.select, placeholder="Type") }}
      {{ render_field(form.search, placeholer="Value") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Search Book</button>
  </form>
</div>
 
 
{% endblock %}